### ISSUE TITLE
Module only allows one Databricks workspace per RSG

### ISSUE THREAD

**Issue by Kumar9676** [data-platform-hq/terraform-azurerm-databricks-ws#14]
Module only allows one Databricks workspace per RSG.

Managed resource group name must be parameterized to accommodate multiple databricks workspaces per resource group.

managed_resource_group_name                         = "${var.resource_group}-databricks"

**Comment by owlleg6** [comment]
Hello @Kumar9676 , since [version 1.7.3](https://github.com/data-platform-hq/terraform-azurerm-databricks-ws/releases/tag/v1.7.3) we have provided an ability to provide custom managed resource group name, thus allowing to deploy multiple Workspaces in the same RG if you provide value to 'managed_resource_group_name' variable. Please give us feedback if it helps!

**Comment by Kumar9676** [comment]
Thank you @owlleg6. I am currently using 1.7.1 and I will upgrade it to the version you suggested.
